services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    env_file:
      - ../stack.env
    environment:
      - TZ=America/Moncton
      - PROXY_DOMAIN=code.shoebottom.ca
    volumes:
      - /docker/appdata/code-server/config:/config
    ports:
      - 8086:8443
    restart: unless-stopped