services:
  nfs:
    image: erichough/nfs-server
    container_name: nfs-server
    restart: unless-stopped
    volumes:
      - /home/isaac/Media:/nfs
      - /lib/modules:/lib/modules:ro
    environment:
      - NFS_EXPORT_0=/nfs * (rw,no_subtree_check)
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    ports:
      - 2049:2049
      - 2049:2049/udp
      - 111:111
      - 111:111/udp
      - 32765:32765
      - 32765:32765/udp
      - 32767:32767
      - 32767:32767/udp