version: '2'
services:
  cloudflare-ddns:
    container_name: cloudflare-ddns
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - ZONE=shoebottom.ca
      - PROXIED=true
    env_file:
      - ../stack.env