version: '3.8'
services:
  nginxpm:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      DISABLE_IPV6: 'true'
    network_mode: host
    volumes:
      - /docker/appdata/nginxpm/data:/data
      - /docker/appdata/nginxpm/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s