version: "3.2"
services:
  redbot:
    container_name: redbot
    image: phasecorex/red-discordbot
    restart: unless-stopped
    volumes:
      - /docker/appdata/redbot/data:/data
    environment:
      - TZ=America/Moncton
networks:
 default:
   name: "ubuntu-server"
   external: true