version: "3.4"
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: no
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=America/Moncton
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=internal
    volumes:
      - /docker/appdata/tdarr/server:/app/server
      - /docker/appdata/tdarr/configs:/app/configs
      - /docker/appdata/tdarr/logs:/app/logs
      - /home/isaac/Media:/media
      - /docker/appdata/tdarr/transcode_cache:/temp