name = "PieceOfWood"
author = "Isaac Shoebottom"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "734ec8190b5786eaacb0b1729dc638bae0a878730c586edf423724bb2066de8b"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
