name = "PieceOfWood"
author = "Isaac Shoebottom"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21ed963f3b6340ed3da8276f7ac2ceabf1b1be8992b7f0c8b4a5fadb43dc5864"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
