name = "PieceOfWood"
author = "Isaac Shoebottom"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc2ce1ece5c1b702fbf943f32031d6428ab1ae7cf95f12c8047e9b412e617b67"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
