name = "PieceOfWood"
author = "Isaac Shoebottom"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "030a1a6c91f503872be7f31c1cd946f33bad5816c1225a312fc809bfa1409210"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
