name = "PieceOfWood"
author = "Isaac Shoebottom"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27447359fd12bb5c110dbb80ae738f73c6231938403af7a12e1c6f6e19f1cbc4"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
