# https://github.com/imputnet/cobalt/blob/main/docs/run-an-instance.md
services:
    cobalt:
        image: ghcr.io/imputnet/cobalt:latest
        restart: unless-stopped
        container_name: cobalt
        init: true
        read_only: true
        ports:
            - 9000:9000/tcp
            # if you're using a reverse proxy, uncomment the next line and remove the one above (9000:9000/tcp):
            #- 127.0.0.1:9000:9000
        environment:
            # replace https://api.cobalt.tools/ with your instance's target url in same format
            API_URL: "https://cobalt.shoebottom.ca/"
            # replace eu-nl with your instance's distinctive name
            API_NAME: "ca-nb-irs"
            # if you want to use cookies when fetching data from services, uncomment the next line and the lines under volume
            # COOKIE_PATH: "/cookies.json"
            # Uncomment to enable api key
            # API_KEY_URL: "file:///keys.json"
        #volumes:
            #- /docker/appdata/cobalt/cookies.json:/cookies.json:ro
            #- /docker/appdata/cobalt/keys.json:/keys.json:ro