services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - START_SSH_SERVER=true
      - BUILTIN_SSH_SERVER_USER=gitea
      - SSH_DOMAIN=git.shoebottom.ca
    volumes:
      - /docker/appdata/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000"
      - "2221:22"