services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - GITEA__server__DISABLE_SSH=false
      - GITEA__server__START_SSH_SERVER=false
      - GITEA__server__BUILTIN_SSH_SERVER_USER=git
      - GITEA__server__SSH_DOMAIN=git.shoebottom.ca
    volumes:
      - /docker/appdata/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000"
      - "2221:22"