version: '3'
services:
  handbrake:
    container_name: handbrake
    image: jlesage/handbrake:latest
    restart: on-failure
    ports:
      - "5800:5800"
    volumes:
      - "/home/isaac:/storage:ro"
      - "/docker/appdata/handbrake/config:/config:rw"
      - "/docker/appdata/handbrake/trash:/trash:rw"
      - "/docker/appdata/handbrake/watch:/watch:rw"
      - "/docker/appdata/handbrake/output:/output:rw"