services:
  gotify:
    container_name: gotify
    hostname: gotify.local
    image: gotify/server:latest
    restart: unless-stopped
    ports:
      - 8085:80
    volumes:
      - "/docker/appdata/gotify/data:/app/data"