version: '2.2'
services:
  jmusicbot:
    image: craumix/jmusicbot:latest
    container_name: jmusicbot
    restart: unless-stopped
    volumes:
     - /docker/appdata/jmusicbot:/jmb/config
networks:
 default:
   name: "ubuntu-server"
   external: true