version: "3"
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    env_file:
      - stack.env
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_SLUG: "all-the-mods-3"
      CF_FILENAME_MATCHER: "6.1.1"
      TZ: "America/Moncton"
      ENABLE_ROLLING_LOGS: "true"
      MAX_MEMORY: "6G"
      VERSION: "1.12.2"
      MOTD: "All The Mods 3"
      DIFFICULTY: "normal"
      SNOOPER_ENABLED: "false"
      ALLOW_FLIGHT: "true"
      SETUP_ONLY: "true"
      USE_SIMD_FLAGS: "true"
      ENABLE_RCON: "true"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /docker/appdata/atm3/data:/data