version: "3.7"

services:
  redis:
    container_name: redis
    image: cgr.dev/chainguard/valkey:latest
    command: --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - /docker/appdata/valkey/data:/data
    networks:
      - searxng
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - 8383:8080
    networks:
      - searxng
    volumes:
      - /docker/appdata/searxng/config:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://searx.shoebottom.ca/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    healthcheck:
      test: ["CMD", "wget http://localhost:8080 -O /dev/null || exit 1"]
      interval: 10s
      timeout: 3s
networks:
  searxng: