version: "3"
services:
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_WARN_ON_HEAD_FAILURE=never # fixes culturalconnections notifcation
      - WATCHTOWER_DISABLE_CONTAINERS="pihole minecraft atm3 handbrake culturalconnections xedit-mirror"
    env_file:
      - ../stack.env
networks:
 default:
   name: "ubuntu-server"
   external: true