version: "3"
services:
  yacht:
    container_name: yacht
    restart: unless-stopped
    network_mode: host
    volumes:
      - /docker/appdata/yacht/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    image: selfhostedpro/yacht

