# Helpful guide: https://therobbiedavis.com/selfhosting-bluesky-with-docker-and-swag/
services:
  pds:
    container_name: pds
    image: ghcr.io/bluesky-social/pds:latest
    ports:
      - 3003:3000
    restart: unless-stopped
    environment:
      - PDS_HOSTNAME=pds.shoebottom.ca
      - PDS_DATA_DIRECTORY=/pds
      - PDS_BLOBSTORE_DISK_LOCATION=/pds/blocks
      - PDS_EMAIL_FROM_ADDRESS=admin@shoebottom.ca
      - PDS_MODERATION_EMAIL_ADDRESS=admin@shoebottom.ca
      - PDS_DID_PLC_URL=https://plc.directory
      - PDS_BSKY_APP_VIEW_URL=https://api.bsky.app
      - PDS_BSKY_APP_VIEW_DID=did:web:api.bsky.app
      - PDS_REPORT_SERVICE_URL=https://mod.bsky.app
      - PDS_REPORT_SERVICE_DID=did:plc:ar7c4by46qjdydhdevvrndac
      - PDS_CRAWLERS=https://bsky.network
      - LOG_ENABLED=true
      - PDS_INVITE_REQUIRED=true
    volumes:
      - /docker/appdata/bluesky/pds:/pds
    env_file:
      - ../stack.env
