version: '3'
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    network_mode: 'host'
    restart: 'unless-stopped'
    group_add:
      - '109' # Render group
    environment:
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
      - JELLYFIN_PublishedServerUrl=https://jellyfin.shoebottom.ca
    volumes:
      - /docker/appdata/jellyfin/etc:/config
      - /docker/appdata/jellyfin/cache:/cache
      - /docker/appdata/jellyfin/lib:/var/lib/jellyfin
      - /docker/appdata/jellyfin/log:/var/log/jellyfin
      - /home/isaac/Media:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/renderD129:/dev/dri/renderD129