version: '3'
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:10.9.3
    network_mode: 'host'
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
      - JELLYFIN_PublishedServerUrl=https://jellyfin.shoebottom.ca
    volumes:
      - /docker/appdata/jellyfin/etc:/etc/jellyfin
      - /docker/appdata/jellyfin/cache:/var/cache/jellyfin
      - /docker/appdata/jellyfin/lib:/var/lib/jellyfin
      - /docker/appdata/jellyfin/log:/var/log/jellyfin
      - /home/isaac/Media:/media