version: '3'
services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    network_mode: 'host'
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
      - JELLYFIN_PublishedServerUrl=https://jellyfin.shoebottom.ca
    volumes:
      - /docker/appdata/jellyfin/etc:/config
      - /docker/appdata/jellyfin/cache:/cache
      - /docker/appdata/jellyfin/lib:/var/lib/jellyfin
      - /docker/appdata/jellyfin/log:/var/log/jellyfin
      - /home/isaac/Media:/media
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools