version: '3.4'
services:
  muse:
    container_name: muse
    image: ghcr.io/museofficial/muse:latest
    restart: unless-stopped
    volumes:
      - /docker/appdata/muse/data:/data
    env_file:
      - ../stack.env
    environment:
      - REGISTER_COMMANDS_ON_BOT=true