services:
  mc:
    container_name: minecraft
    image: itzg/minecraft-server:java21-alpine
    restart: unless-stopped
    ports:
      - "25565:25565/tcp" # minecraft
      - "25565:25565/udp" # plasmo-voice
      - "25566:8123" # dynmap
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      TZ: "America/Moncton"
      ENABLE_ROLLING_LOGS: "true"
      ENABLE_AUTOPAUSE: "true"
      MAX_TICK_TIME: -1
      MAX_MEMORY: "6G"
      VERSION: "1.21.4"
      MOTD: "Let's get it started in here"
      SEED: "-2694942683531129739"
      DIFFICULTY: "normal"
      SNOOPER_ENABLED: "false"
      ALLOW_FLIGHT: "true"
      ENABLE_RCON: "true"
      USE_AIKAR_FLAGS: "true"
      OPS: "IsaacDaybreak"
      PACKWIZ_URL: "https://git.shoebottom.ca/IsaacShoebottom/compose/raw/branch/master/minecraft/pack/pack.toml"
      REMOVE_OLD_MODS: "true"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"
      MODRINTH_ALLOWED_VERSION_TYPE: "alpha"
      # Disabled mods:
      #   dynmap (Not updated)
      #   disable-portal-checks (Not updated)
      #   fastback (Not updated)
      #   headfix (Not updated)
      #   faster-random (Not updated)
      #   achievements-optimizer (Not updated)
      #   jei (Not updated)
      #   railoptimization (Not updated)
      #   modernfix (Not updated)
    volumes:
      - /docker/appdata/minecraft:/data