
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    network_mode: host
    expose:
      - "11434"
    restart: unless-stopped
    volumes:
      - /home/isaac/Ollama:/root/.ollama