networks:
  default:
    external:
      name: ollama-network
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: ollama-network

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - /home/isaac/Ollama:/root/.ollama
    networks:
      - ollama-network
