networks:
  ollama-network:
    external:
      name: ollama-network

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - /home/isaac/Ollama:/root/.ollama
    networks:
      - ollama-network
