version: '3'
services:
  server:
    container_name: tes3mp
    image: "tes3mp/server:0.8.1"
    environment:
      - TES3MP_SERVER_HOSTNAME="Isaac's Server"
    volumes:
      - "/docker/appdata/tes3mp/data:/server/data"
    ports:
      - "25575:25565/udp"
networks:
 default:
   name: "ubuntu-server"
   external: true