version: '3'
services:
  server:
    container_name: tes3mp
    restart: unless-stopped
    image: "tes3mp/server:0.8.1"
    environment:
      - TES3MP_SERVER_HOSTNAME="Isaac's Server"
      - TES3MP_SERVER_PORT=25575
      # Disable master server
      - TES3MP_SERVER_ENABLED=false
    volumes:
      - "/docker/appdata/tes3mp/data:/server/data"
    ports:
      - "25575:25575/udp"