services:
    wrapperr:
        image: ghcr.io/aunefyren/wrapperr:latest
        container_name: wrapperr
        restart: unless-stopped
        ports:
          - 8282:8282
        volumes:
          - /docker/appdata/wrapperr/config:/app/config
    tautulli:
        image: ghcr.io/tautulli/tautulli:latest
        container_name: tautulli
        restart: unless-stopped
        environment:
          - TZ=America/Moncton
        ports:
          - 8181:8181
        volumes:
          - /docker/appdata/tautulli/config:/config